{{- if .Values.chart.enabled }}
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    #argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.95.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    classRef:
      name: {{ .Values.cluster.classRef.name }}
      namespace: vmware-system-vks-public
    version: {{ .Values.cluster.vkr }}
    variables:
      - name: vmClass
        value: {{ .Values.cluster.vmClass }}
      - name: storageClass
        value: {{ .Values.cluster.storageClass }}
    controlPlane:
{{- with .Values.cluster.controlPlane }} 
{{ toYaml . | indent 6 -}}
{{ end }}  
    workers:
      machineDeployments:
{{- with .Values.cluster.workers.machineDeployments }} 
{{ toYaml . | indent 6 -}}
{{ end }}  
{{ end -}}