{{- if .Values.chart.enabled }}
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: vks-cluster-01
  namespace: vks-clusters-w33y7
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.95.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    classRef:
      name: builtin-generic-v3.7.0
      namespace: vmware-system-vks-public
    version: v1.36.2---vmware.2-vkr.3
    variables:
      - name: vmClass
        value: best-effort-xsmall
      - name: storageClass
        value: home-m01-cl01-optimal-datastore-default-policy-autoraid
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=photon
    workers:
      machineDeployments:
        - class: node-pool
          name: vks-cluster-01-np-01
          replicas: 1
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=photon
{{ end -}}