apiVersion: secretstore.vmware.com/v1alpha1
kind: KeyValueSecret
metadata:
  name: vks-clustername-example           ## set the same as spec.name for ease of use
spec:
  name: vks-clustername-example           ## must start with vks_cluster_name as this is how polices are scoped         
  data:
    - key: username
      value: admin
    - key: password
      value: password