apiVersion: secretstore.vmware.com/v1alpha1
kind: KeyValueSecret
metadata:
  name: example
spec:
  name: example
  data:
    - key: username
      value: admin
    - key: password
      value: password