{{- if .Values.chart.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vcfa-cluster-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    vault:
      server: https://secret-store:8200
      # grab this from kubectl get secret server-cert -n svc-secret-store-rvlg5 -o jsonpath='{.data.ca\.crt}'
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR1RENDQXFDZ0F3SUJBZ0lVWlI3OVVTQnhhVVZpNlRBV3h4WEFicllQTUxrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0FEQWVGdzB5TmpBNU1qWXhOek0yTkRkYUZ3MHpOakE1TWpNeE56TTJORGRhTUFBd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEaVl6RzlOQ2xlTHpuN0NNQVNLaC9GY2dCS1I1eW1yTzBmCmlkejRpL1lmRy8vZkEzUWVaMUUrR0xGY3l4L0JRWkw3VmxrQ3R2c2doM2IvWVp5aTBsVDBuVE5pL1ppZXRURU4KSDN5ZGNmVjFKRWU5T21QcHhGVWMvbHExN0lOZ2I4cFMxQmQyMDk0bWNhWDZtWlpOSW5tS1ByQWJ2RkJPb1lyYwpkbEtvQmhyRmFqa1E2ckF3bWNnTmRFcE8vbXNJSW1POGd0MVpCdXUwWjB3ZGhiYldPK3NDVVRsaTJzSWhZK1NNCnpRL0ZXZnZ4Q2lETmJhTnBHc3puRGZWRmo4ZW9TZlVDZ3lETVBJdURkMzJDeDY4VDNuZzQwTUZKRGRleHhMdDMKcnlROUlrdkRJbStPNGVvWFZTZzc5WmhSU210L2ZGdjBDT05aQ3k5KzNGS2NibGZ2b3FNSEFnTUJBQUdqZ2dFbwpNSUlCSkRBT0JnTlZIUThCQWY4RUJBTUNCYUF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0RBWURWUjBUCkFRSC9CQUl3QURDQjdnWURWUjBSQVFIL0JJSGpNSUhnZ2oxelpXTnlaWFF0YzNSdmNtVXRjMlZ5ZG1salpTNXoKZG1NdGMyVmpjbVYwTFhOMGIzSmxMWEoyYkdjMUxuTjJZeTVqYkhWemRHVnlMbXh2WTJGc2dqVnpaV055WlhRdApjM1J2Y21VdWMzWmpMWE5sWTNKbGRDMXpkRzl5WlMxeWRteG5OUzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiSUlNCmMyVmpjbVYwTFhOMGIzSmxnaFJ6WldOeVpYUXRjM1J2Y21VdGMyVnlkbWxqWllJNWMyVmpjbVYwTFhOMGIzSmwKTFhObGNuWnBZMlV1ZG10ekxYWmhkV3gwTFdsdWFtVmpkRzl5TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzZ2dscwpiMk5oYkdodmMzUXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRW5UaWhvQjNPM3ZPUUMrMlBpZVMzeGVoWkxXCnV5VkdtZnB0TXE4aW92RTV4bXVmRkpqTG9WSWw2V2dvck5XWHNTS2NNcnU3MFJBNE52Zks0RG5hamRqM05wNjIKdkNxSHZ4N0pqMFR4M1NuM2xNQXJ2SldPWjgvNmUvZTBZamU3MmpoMXF4QWZjbnVlbHlNaExYNWJmUEN3RFoyNAo1Rjh6aEZaZzN3bUNGa3VXaGdRVkZMdEJVcyt4YTVPTHplMlF4YzkxcklMQXJlQTkyMzVSTDRPR1d2QloxR0IwCllSdHh5bC9xcHZHcllVVjdLelgwTHh5bXA5VUdIUXpZNDlVQkpya2J1bHpXWFdxRWM3Tm94Zzg3T3dBSTRjMWUKM1RDSGVtRmI3Sms2bm5DVVc4MmcxcFlIcGk5VXJJaHl0VU9GVEdRSjVqd3pmY1lYRnpQTVY2REUvMFU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      path: secret
      version: v2
      auth:
        kubernetes:
          # The mount path follows the pattern kubernetes-<supervisor_ns>-<cluster_name>
          mountPath: kubernetes-vks-clusters-mfm9f-dev-01
          # The role follows the pattern <supervisor_ns>-<cluster_name>
          role: vks-clusters-mfm9f-dev-01
          # The ServiceAccount ESO uses to authenticate
          serviceAccountRef:
            name: secret-store-sa
            namespace: external-secrets
{{ end -}}