{{- if .Values.chart.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externaldns-kerberos-password
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vcfa-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: externaldns-kerberos-password
  data:
    - secretKey: KRB_PASSWORD
      remoteRef:
        key: vks-clusters-mfm9f/dev-01-external-dns-krb-password
        property: KRB_PASSWORD
        decodingStrategy: Base64
{{ end -}}