{{- if .Values.vksclusters.region01.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-store-sa
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
{{ end -}}
